### ISSUE TITLE
Python 3  or 2  ? SyntaxError: Non-ASCII character '\xe2'  

### ISSUE THREAD

**Issue by wordyallen** [datamade/chi-councilmatic#116]
I'm getting an error when I run

`python manage.py migrate --no-initial-data`

Which seems like its trying to run with python 3.  However, when I run

`python3 manage.py migrate --no-initial-data`

I get `No module named 'django'  ...

Is there something wrong with my python configuration? I'm using the default ubuntu 14 box from digital ocean. 

Thanks!

**Comment by cathydeng** [comment]
hey @wordyallen - this is python 3. you should have django installed once you install django-councilmatic (`pip install -r requirements.txt`). currently requirements.txt grabs the most recent version of django-councilmatic from github - if you're forking this rather than working on chi-councilmatic, I'd recommend fixing the django-councilmatic version in your requirements.txt (most recent version is 0.5.1)

**Comment by wordyallen** [comment]
should I run pip3? for linux distro that has both? 

I'm going to follow this guide to make sure pip is working with python 3...

http://stackoverflow.com/questions/29712519/how-to-use-pip3-with-python-3-4

**Comment by fgregg** [comment]
Definitely use pip3
