### ISSUE TITLE
Committe view on alderman pages is not working

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#195]
I suspect caching https://chicago.councilmatic.org/person/moreno-proco-joe-b1e0d8e0205d/?view=committees

**Comment by reginafcompton** [comment]
Yep. It's the advanced cache library, which does not play well with the nav pills. I disabled caching for the time being...I will reopen this issue in django-councilmatic, since this is an app-wide problem and also because I'd like to refactor how the tabs work, in general (use JS, rather then sending a request).

**Comment by fgregg** [comment]
Let's not disable caching for this pretty minor page. It's slows down the whole site.
