### ISSUE TITLE
There are 53 members of the rules committee but only 50 aldermen

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#224]
https://chicago.councilmatic.org/committee/committee-on-committees-rules-and-ethics-d05d22b44a74/

**Comment by evz** [comment]
That's because there are 3 Sophia Kings:
https://chicago.councilmatic.org/person/king-sophia-f7bbd9c416e4/
https://chicago.councilmatic.org/person/sophia-d-king-184609cbc49b/
https://chicago.councilmatic.org/person/king-sophia-d-df83178f173a/

And 2 Milly Santiagos
https://chicago.councilmatic.org/person/santiago-milagros-s-f4b095aa4479/
https://chicago.councilmatic.org/person/santiago-milagros-0aac9a573f11/

**Comment by evz** [comment]
This is also interesting. A bill only sponsored by Sophia King shows up as being sponsored by all three Sophia Kings:

https://chicago.councilmatic.org/legislation/or-2017-265/

**Comment by fgregg** [comment]
fixed
