### ISSUE TITLE
legislation typo showing the year 3013

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#49]
Typo on the Clerk's website showing a year for an action far into the future: https://chicago.legistar.com/LegislationDetail.aspx?ID=1041698&GUID=0BC5A00D-7559-4162-A413-3E2B067537C9

I just reached out to their office to let them know. Will keep track of the status in this issue.

**Comment by cathydeng** [comment]
this probably won't get fixed by tomorrow, so we should handle it somehow. we def don't want the 3013 bill showing up on the homepage, or as the top result on the search page. some questions:

1. do we want to fix the date, or remove the action? I'm leaning towards removing the action (& keeping the bill), but idk
2. do we want to look for suspicious dates in general, or just handle them individually?
3. do we want to make data tweaks in django councilmatic or chicago councilmatic?

thoughts @fgregg?

**Comment by fgregg** [comment]
I think it can make sense to 

* Filter impossible dates in the application layer
* Correct dates, if possible, in the data layer

Since the application layer is where we are more likely to notice bugs, let's have anything that we filter out get logged to sentry. @evz can help with that.

**Comment by cathydeng** [comment]
now we need to run `python manage.py fixdata` after loaddata
