### ISSUE TITLE
Link to municipal code relevant

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#98]
For bills like http://chicago.councilmatic.org/legislation/o-2015-4229/

http://chicagocode.org/2/2-56/
http://chicagocode.org/2/2-156/

**Comment by fgregg** [comment]
attn @krues8dr!

**Comment by krues8dr** [comment]
Excellent, that looks like it'll work great!  FWIW, I'm grabbing structures and sections with these regex: https://github.com/opengovfoundation/chicagocode/blob/master/includes/class.Chicago.inc.php#L25-L26

But I have the luxury here of running against structured data where I know these patterns will always match.  You might end up with some false positives (I'm thinking of addresses & dates, etc.), so checking for a proceeding keyword that matches my set there (Chapter, Title, etc) could help with that, but I wouldn't bother until you see actual problems.  

There are a couple of sections where this is might be problematic, because Chicago has divisions that are not accounted for in its numbering system, so we have to fake it in the URLs to make it work.  For example, https://chicagocode.org/2/2-8/ has four divisions (I-IV, that we've made a mess of the roman numerals.  ack.), which end up in the urls.  That *probably* won't affect you since it's just above the actual sections which don't keep this identifier in the URL, but it's something to watch out for!

**Comment by krues8dr** [comment]
One thing you might want to do here is restrict `\d` to `{1,2}` on Titles and Chapters instead of `+` as you have it now, which will reduce the number of false positives on numeric ranges.  So far, Chicago hasn't broken 100 of either afaik.
